------------------------------------------------------------------------------------------------------<br>
<h3 style="background:#87a1c2; color:#ffffff; padding:20px; border-radius:5px;">✍ EJERCICIOS NUMPY PARA @EGGERS</h3><br>
------------------------------------------------------------------------------------------------------<br>

1. Crea un vector entre 7 y 66.
2. Invierte el vector generado anteriormente.
3. Matriz de 4x4 con valores entre 0 y 15.
4. Crea la matriz identidad de 5x5.
5. Crea una matriz de 5x5 donde la posición central y todas las posiciones que conforman el marco valgan 1 y el resto 0.
6. Matriz de 4x4 donde cada fila valga entre 3 y 0. Valores in crescendo.
7. Crea un array de ceros de 2x7.
8. Crea un array de ceros de 5x4 excepto toda la primera fila que valga 1.
9. Crea un array que represente una tabla de ajedrez. Negras 1 y blancas 0.

Importamos la librería Numpy

In [1]:
import numpy as np

1. Crea un vector entre 7 y 66

In [21]:
vector = np.arange(7, 66)

2. Invierte el vector generado anteriormente.

In [32]:
vector_invertido = vector[::-1]

3. Matriz de 4x4 con valores entre 0 y 15.

In [59]:
matriz = np.linspace(0, 15, num=16)
matriz.reshape(4,4)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

4. Crea la matriz identidad de 5x5.

In [61]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

5. Crea una matriz de 5x5 donde la posición central y todas las posiciones que conforman el marco valgan 1 y el resto 0.

In [90]:
a = np.ones((5, ), dtype=int)
b = [1, 0, 0, 0, 1]
c = [1, 0, 1, 0, 1]

matriz = np.vstack((a, b, c, b, a))
matriz


array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 1, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

6. Matriz de 4x4 donde cada fila valga entre 3 y 0. Valores in crescendo.

In [98]:
matriz = np.array(np.linspace(0,3, 4, dtype=int))
for i in range(3):
    b = np.array(np.linspace(0,3, 4, dtype=int))
    matriz = np.vstack((matriz, b))
matriz

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

7. Crea un array de ceros de 2x7.

In [46]:
ceros = np.zeros((2,7), dtype=int)
ceros

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

8. Crea un array de ceros de 5x4 excepto toda la primera fila que valga 1.

In [97]:
matriz = np.ones((1,5), dtype=int)
for i in range(3):
    b = np.zeros((1,5), dtype=int)
    matriz = np.vstack((matriz, b))

matriz

array([[1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

9. Crea un array que represente una tabla de ajedrez. Negras 1 y blancas 0.

In [32]:
matriz = np.zeros((8,8), dtype=int)
for index1, array in enumerate(matriz):
    if index1 % 2 == 0:
        for index2, i in enumerate(array):
            if index2 % 2 != 0:
                array[index2] = 1 
                     
    elif index1 % 2 != 0:
        for index3, i in enumerate(array):
            if index3 % 2 == 0:
                array[index3] = 1