------------------------------------------------------------------------------------------------------<br>
<h3 style="background:#87a1c2; color:#ffffff; padding:20px; border-radius:5px;">1.- ✍ Introducción.</h3><br>
------------------------------------------------------------------------------------------------------<br>

In [1]:
# importar numpy con alias np
import numpy as np

------------------------------------------------------------------------------------------------------<br>
<h3 style="background:#87a1c2; color:#ffffff; padding:20px; border-radius:5px;">2.- ✍ Funciones matemáticas y constantes</h3><br>
------------------------------------------------------------------------------------------------------<br>

In [2]:
np.pi

3.141592653589793

In [3]:
np.e

2.718281828459045

In [4]:
np.log(10)

2.302585092994046

In [5]:
# coeficiente de correlación de Pearson
x = np.array([
    [1, 2, 3, 4, 5, 6, 8, 12, 11, 19],
    [7, 8, 9, 10, 11, 12, 13 ,14 ,15 ,16]
])
np.corrcoef(x)

array([[1.       , 0.9361986],
       [0.9361986, 1.       ]])

In [6]:
# media aritmética
np.mean(x)

9.3

In [7]:
# suma acumulada de los valores del array
np.cumsum(x)

array([  1,   3,   6,  10,  15,  21,  29,  41,  52,  71,  78,  86,  95,
       105, 116, 128, 141, 155, 170, 186], dtype=int32)

------------------------------------------------------------------------------------------------------<br>
<h3 style="background:#87a1c2; color:#ffffff; padding:20px; border-radius:5px;">3.- ✍ Generación de array-s y alguna operación matemática</h3><br>
------------------------------------------------------------------------------------------------------<br>

In [8]:
# Generar array
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [9]:
# Tipo de dato
a = np.array([1, 2, 3.0, 7.67])
print(a.dtype)

float64


In [10]:
# Generar array de tipo flotante
np.array([1, 2, 3, 9, 13], dtype=float)

array([ 1.,  2.,  3.,  9., 13.])

In [11]:
# De tipo complejo
np.array([1, 2, 3, 4 , 5], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [12]:
a

array([1.  , 2.  , 3.  , 7.67])

In [13]:
# conversión a tipo entero
a.astype(int)

array([1, 2, 3, 7])

In [14]:
# un nuevo array de forma y tipo dados, sin inicializar las entradas.
s = np.empty((3,3))
print (s)
s.shape

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 7.27264631e-321]
 [8.90060779e-307 1.61759680e+069 8.73989984e+245]]


(3, 3)

In [15]:
X, Y = 5, 5
print (np.empty(25))
# matriz de 5x5 sin inicializar valores
j = np.empty(25).reshape(X, Y)
# matrices de 5x5 con valores aleatorios
k = np.random.rand(25).reshape(X, Y)
l = np.random.rand(25).reshape(X, Y)

[8.67164411e-312 7.16395186e-322 0.00000000e+000 0.00000000e+000
 7.56587583e-307 1.16095484e-028 2.96977369e+222 1.96086580e+243
 4.19334286e+228 9.62881650e+199 1.09745563e+248 7.26611031e+223
 3.71326426e+161 6.10941611e+223 1.10663757e+136 5.28595592e-085
 2.93625480e-062 1.75300433e+243 9.24896136e+135 4.24819624e+180
 6.48224637e+170 3.67145870e+228 2.72831122e-057 2.12199579e-312
 3.75603081e-317]


In [16]:
# Suma de dos arrays
j = j + l
print (j)
# Multiplicación de dos arrays
j = j * l
print (j)

[[6.44620930e-001 3.45960855e-001 9.63052303e-001 7.15897969e-001
  3.48471558e-001]
 [6.68266789e-002 2.96977369e+222 1.96086580e+243 4.19334286e+228
  9.62881650e+199]
 [1.09745563e+248 7.26611031e+223 3.71326426e+161 6.10941611e+223
  1.10663757e+136]
 [1.53725056e-001 6.50476501e-001 1.75300433e+243 9.24896136e+135
  4.24819624e+180]
 [6.48224637e+170 3.67145870e+228 1.69605208e-002 7.47948672e-002
  9.09683425e-001]]
[[4.15536143e-001 1.19688913e-001 9.27469737e-001 5.12509902e-001
  1.21432427e-001]
 [4.46580502e-003 6.00270004e+221 1.73514157e+243 2.47415538e+227
  7.33036991e+199]
 [9.11512126e+247 2.18326145e+223 2.16627639e+161 3.07397003e+223
  3.90913344e+135]
 [2.36313928e-002 4.23119678e-001 1.33128843e+242 6.96722620e+135
  3.30258763e+180]
 [6.21060268e+170 1.63275495e+226 2.87659267e-004 5.59427216e-003
  8.27523933e-001]]


------------------------------------------------------------------------------------------------------<br>
<h3 style="background:#87a1c2; color:#ffffff; padding:20px; border-radius:5px;">4.- ✍ Indexación de Array-s y búsqueda de elementos</h3><br>
------------------------------------------------------------------------------------------------------<br>

In [17]:
# generar array
z = np.array([
    [1, 2, 3, 4, 5, 6, 8, 12, 11, 19],
    [7, 8, 9, 10, 11, 12, 13 ,14 ,15 ,16]
])
print (z.shape)

(2, 10)


In [18]:
# segunda fila
z[1]

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [19]:
# corte entre segunda fila y segunda columna
z[1, 1]

8

In [20]:
# de la primera fila el corte con las columnas desde la 0 hasta la 2
z[0, 0:3]

array([1, 2, 3])

In [21]:
# corte de la primera fila con las columnas desde la primera hasta la última dando saltos de tres en tres
z[0, ::3]

array([ 1,  4,  8, 19])

In [22]:
# penúltima posición de la segunda fila
z[1, -2]

15

------------------------------------------------------------------------------------------------------<br>
<h2 style="background:#87a1c2; color:#ffffff; padding:20px; border-radius:5px;">5. Generar array-s</h2>

* A partir de array-s generados: `array`, `copy`
* 1 y 0: `empty`, `eye`, `ones`, `zeros`, `*_like`
* Rangos: `arange`, `linspace`, `logspace`, `meshgrid`
* Aleatorios: `rand`, `randn`

------------------------------------------------------------------------------------------------------<br>



In [23]:
# matriz identidad de 3x3
np.identity(3).astype(int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [24]:
# saber diemensión de la matriz de la celda anterior
_.shape

(3, 3)

In [25]:
# matriz de unos
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [26]:
# matriz de ceros
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [27]:
# matriz identidad de 2x2
identidad = np.identity(2)
identidad

array([[1., 0.],
       [0., 1.]])

In [28]:
identidad.shape

(2, 2)

In [29]:
# matriz de unos con la dimensión de la matriz identidad
np.ones(identidad.shape)

array([[1., 1.],
       [1., 1.]])

------------------------------------------------------------------------------------------------------<br>
<h3 style="background:#87a1c2; color:#ffffff; padding:20px; border-radius:5px;">6.- ✍ Rangos.</h3><br>

* linspace(start, stop, num=50)
* meshgrid 

------------------------------------------------------------------------------------------------------<br>


In [30]:
# vector del 0 al 10 separarado proporcionalmente en 5 rangos. Parecido al meshgrid
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

------------------------------------------------------------------------------------------------------<br>
<h3 style="background:#87a1c2; color:#ffffff; padding:20px; border-radius:5px;">7.- ✍ Más operaciones con Array-s.</h3><br>

* Funciones matemáticas: `sin`, `cos`, `sqrt`, `exp`, ...
* Operadores lógicos: `<`, `~`, ...
* Funciones lógicas: `all`, `any`, `isnan`, `allclose`, ...

------------------------------------------------------------------------------------------------------<br>


In [31]:
# array del 0 al 8 de uno en uno
a = np.arange(3*3)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
# del 3 al 6 de uno en uno en coma flotante
a = np.arange(3., 7.)
a

array([3., 4., 5., 6.])

In [33]:
# array del 0 al 6 de uno en uno y dimensión de 2x3
a = np.arange(2 * 3).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [34]:
# raíz cuadrada de una matriz
np.sqrt(a)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798]])

In [35]:
# números complejos
np.arange(-3, 3).astype(complex)

array([-3.+0.j, -2.+0.j, -1.+0.j,  0.+0.j,  1.+0.j,  2.+0.j])

In [36]:
# generación de 2 vectores
a = np.arange(-1, 8)
b = np.zeros(9).astype(int)
a, b

(array([-1,  0,  1,  2,  3,  4,  5,  6,  7]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0]))

In [37]:
# comparación booleana
a < b

array([ True, False, False, False, False, False, False, False, False])

In [38]:
# si se cumple la condición en alguna de las posiciones es True
np.any(a < b)

True

In [39]:
# si se cumple la condición en todas las posiciones es True
np.all(a < b)

False

<h3>👏👏👏 You guys rock !!!</h3>